services:
  - type: web
    name: my-laravel-app
    env: docker
    build:
      dockerfile: Dockerfile
    port: 80
    healthCheckPath: /health
    plan: starter
    autoDeploy: true
    branch: main
    routes:
      - type: http
        name: my-laravel-app
        domain: your-custom-domain.com  # Cambia esto si tienes un dominio personalizado
