services:
  - type: web
    name: my-laravel-app
    env: docker
    dockerfile: Dockerfile
    port: 9000
    buildCommand: ""
    startCommand: "php-fpm"
    healthCheckPath: "/"
    healthCheckInterval: 30s
    healthCheckTimeout: 10s
